CREATE TABLE project_members
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    project_id BIGINT                                  NOT NULL,
    user_id    VARCHAR(255)                            NOT NULL,
    type       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_project_members PRIMARY KEY (id)
);

CREATE TABLE projects
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at              TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at              TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    name                    VARCHAR(255)                            NOT NULL,
    location                VARCHAR(255)                            NOT NULL,
    specifier               VARCHAR(255)                            NOT NULL,
    type                    VARCHAR(255)                            NOT NULL,
    estimated_delivery_date date                                    NOT NULL,
    status                  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_projects PRIMARY KEY (id)
);

ALTER TABLE projects
    ADD CONSTRAINT ukey_projects_name UNIQUE (name);

ALTER TABLE project_members
    ADD CONSTRAINT fkey_project_members_on_projects_project_id FOREIGN KEY (project_id) REFERENCES projects (id);